#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Opt-in startup metadata only; no torch import, tensor data, or model calls.

Adapted from the pinned ab6660699 emitter (`build/startup_observer.py`, kept
read-only) for the NEW (83252ea89) call sites generated by
`prepare_startup_observer_83252ea89.py`. Three stages lost kwargs in the
upstream refactor (see OBSERVER-PORT-NOTES.md "Emitter adaptation"):

  * engine_final no longer runs in a per-worker loop, so `kv_cache_configs`
    (the full list, used to recover `worker_index` by identity) and the
    matching per-worker `available_memory` entry are out of scope.
  * worker_preallocation / worker_postbind no longer receive `attn_groups`
    (backend + spec per attention-builder group -- it now lives on the model
    runner, one frame up) or `cache_dtype` (dropped from `init_kv_cache`'s
    signature entirely).

Only generated, pinned-source call sites invoke emit(). Failures mark C4 receipts
incomplete on stderr and do not change native execution. Alias IDs are opaque,
deterministic within each snapshot, not addresses or cross-process identifiers.
Read-only sizing properties are evaluated; get_kv_cache_spec/backend/model methods
are never called. Receipt completeness/qualification is an external gate.

Every hook here accepts exactly what its NEW call site supplies. A field that
genuinely cannot be derived from what is in scope is recorded as `null` and
named in a top-level `missing_fields` list -- snapshot() never raises KeyError
for an absent legacy kwarg.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
import json
import math
import os
from pathlib import Path
import re
import socket
import stat
import sys
from zoneinfo import ZoneInfo

SCHEMA = 'vllm-startup-observer-v1-83252ea89'
STAGES = ('engine_projection', 'engine_final', 'worker_preallocation', 'worker_postbind')
SPEC_FIELDS = (
    'block_size', 'storage_block_size', 'page_size_bytes', 'page_size_padded',
    'num_kv_heads', 'head_size', 'head_size_v', 'sliding_window',
    'cache_dtype_str', 'compress_ratio', 'alignment', 'model_version',
    'extra_retained_tokens', 'non_causal',
)
# MambaSpec (also covers GDN/"KDA"-style linear-attention groups: mamba_type
# distinguishes MAMBA1/MAMBA2/SHORT_CONV/LINEAR/GDN_ATTN --
# vllm/v1/attention/backends/registry.py:MambaAttentionBackendEnum, no
# separate KDA spec class exists in this tree) -- all plain scalars, additive
# to SPEC_FIELDS and inert (getattr MISSING-skips) for non-Mamba specs.
MAMBA_SPEC_FIELDS = (
    'mamba_type', 'mamba_cache_mode', 'num_speculative_blocks',
    'num_prefill_checkpoint_blocks', 'prefill_checkpoint_alignment',
    'num_heads', 'tokens_per_state', 'tp_replicated',
)
CONFIG_FIELDS = {
    'model_config': ('max_model_len', 'original_max_model_len'),
    'scheduler_config': ('max_num_batched_tokens', 'max_num_seqs',
                         'disable_hybrid_kv_cache_manager'),
    'cache_config': ('cache_dtype', 'block_size', 'kv_cache_memory_bytes',
                     'num_gpu_blocks_override', 'enable_prefix_caching',
                     'mamba_cache_mode'),
    'parallel_config': ('tensor_parallel_size', 'pipeline_parallel_size',
                        'decode_context_parallel_size', 'prefill_context_parallel_size',
                        'rank', 'data_parallel_rank', 'node_rank'),
    'speculative_config': ('method', 'num_speculative_tokens',
                           'speculative_draft_tensor_parallel_size'),
}
MISSING = object()


def scalar(value):
    if value is None or type(value) in (bool, int, str):
        return value
    if type(value) is float and math.isfinite(value):
        return value
    if isinstance(value, Enum):
        return scalar(value.value)
    raise TypeError('non-scalar metadata')


def metadata_text(value):
    # Do not stringify arbitrary objects (in particular tensors/configs).
    if type(value) is str:
        return value
    kind = type(value)
    if kind.__module__ == 'torch' and kind.__name__ in ('dtype', 'device'):
        return str(value)
    raise TypeError('unsupported dtype/device metadata')


def scalar_fields(obj, names):
    result = {}
    for name in names:
        value = getattr(obj, name, MISSING)
        if value is not MISSING:
            result[name] = scalar(value)
    return result


def class_name(obj):
    cls = obj if isinstance(obj, type) else type(obj)
    return cls.__module__ + '.' + cls.__qualname__


def spec_metadata(spec):
    result = {'class': class_name(spec)}
    # Aggregate page_size_bytes on alias-expanded uniform specs double-counts
    # storage; omit it there and record explicit inner specs instead.
    inner = getattr(spec, 'kv_cache_specs', None)
    selected = tuple(n for n in SPEC_FIELDS if inner is None or n != 'page_size_bytes')
    result.update(scalar_fields(spec, selected))
    dtype = getattr(spec, 'dtype', MISSING)
    if dtype is not MISSING:
        result['dtype'] = metadata_text(dtype)
    # MambaSpec-only: per-state shape/dtype tuples (non-scalar, need explicit
    # traversal) plus the read-only state_content_size_bytes sizing property.
    dtypes = getattr(spec, 'dtypes', MISSING)
    if dtypes is not MISSING:
        result['dtypes'] = [metadata_text(d) for d in dtypes]
    shapes = getattr(spec, 'shapes', MISSING)
    if shapes is not MISSING:
        result['shapes'] = [integer_list(s) for s in shapes]
    result.update(scalar_fields(spec, MAMBA_SPEC_FIELDS))
    state_bytes = getattr(spec, 'state_content_size_bytes', MISSING)
    if state_bytes is not MISSING:
        result['state_content_size_bytes'] = scalar(state_bytes)
    if inner is not None:
        result['per_layer'] = specs_metadata(inner)
    return result


def specs_metadata(specs):
    return {name: spec_metadata(specs[name]) for name in sorted(specs)
            if type(name) is str}


def groups_metadata(groups):
    # is_eagle_group is the existing draft/MTP annotation on KVCacheGroupSpec;
    # unchanged shape from OLD.
    return [dict(group_id=i, layer_names=[scalar(n) for n in group.layer_names],
                 is_eagle_group=scalar(group.is_eagle_group),
                 spec=spec_metadata(group.kv_cache_spec))
            for i, group in enumerate(groups)]


def config_metadata(config):
    return {section: scalar_fields(obj, names)
            for section, names in CONFIG_FIELDS.items()
            if (obj := getattr(config, section, None)) is not None}


def cache_metadata(cache, missing_fields):
    # NEW's KVCacheTensor renamed `shared_by` -> `layers` (still the layer
    # names backed by this allocation, in L order) and added layer_stride /
    # block_stride / offset (the byte-packing arithmetic for that grouping).
    # Emitted key is renamed to match; the OLD name is tried as a fallback so
    # this keeps working if a caller still supplies an OLD-shaped tensor.
    tensors = []
    for t in cache.kv_cache_tensors:
        entry = dict(size_bytes=scalar(t.size))
        layer_names = getattr(t, 'layers', MISSING)
        if layer_names is MISSING:
            layer_names = getattr(t, 'shared_by', MISSING)
        if layer_names is MISSING:
            entry['layer_names'] = None
            missing_fields.append('cache.allocations[].layer_names')
        else:
            entry['layer_names'] = [scalar(n) for n in layer_names]
        for packing_field in ('layer_stride', 'block_stride', 'offset'):
            value = getattr(t, packing_field, MISSING)
            if value is not MISSING:
                entry[packing_field] = scalar(value)
        tensors.append(entry)
    allocated = sum(t['size_bytes'] for t in tensors)
    blocks = scalar(cache.num_blocks)
    return dict(num_blocks=blocks, groups=groups_metadata(cache.kv_cache_groups),
                allocations=tensors, allocation_bytes=allocated,
                allocation_bytes_per_pool_block=(allocated // blocks
                    if blocks and allocated % blocks == 0 else None))


def aliases_metadata(aliases):
    return {scalar(name): scalar(aliases[name]) for name in sorted(aliases)}


def declared_aliases(forward_context):
    # No repeated layer-discovery or get_kv_cache_spec calls.
    result = {}
    for name in sorted(forward_context):
        target = getattr(forward_context[name], 'kv_sharing_target_layer_name', None)
        if target:
            result[scalar(name)] = scalar(target)
    return result


class Identities:
    """Retain CPU object references for snapshot lifetime; emit sequential IDs only."""
    def __init__(self):
        self.objects = []

    def label(self, obj, prefix):
        for i, known in enumerate(self.objects):
            if known is obj:
                return f'{prefix}{i + 1}'
        self.objects.append(obj)
        return f'{prefix}{len(self.objects)}'


def integer_list(values):
    result = []
    for value in values:
        if type(value) is not int:
            raise TypeError('non-concrete shape/stride')
        result.append(value)
    return result


def view_metadata(tensor, tensors, storages):
    # These operations read existing tensor/storage metadata only. No data_ptr,
    # conversion, indexing, value reads, copies, device transfer or CUDA sync.
    storage = tensor.untyped_storage()
    return dict(tensor_id=tensors.label(tensor, 't'), storage_id=storages.label(storage, 's'),
                shape=integer_list(tensor.shape), stride=integer_list(tensor.stride()),
                storage_offset_elements=scalar(tensor.storage_offset()),
                dtype=metadata_text(tensor.dtype), device=metadata_text(tensor.device),
                storage_bytes=scalar(storage.nbytes()),
                view_bytes=scalar(tensor.numel()) * scalar(tensor.element_size()))


def tensor_snapshots(raw_tensors, views):
    tensors, storages = Identities(), Identities()
    raw = {}
    storage_layers = {}
    for name in sorted(raw_tensors):
        metadata = view_metadata(raw_tensors[name], tensors, storages)
        raw[name] = metadata
        storage_layers.setdefault(metadata['storage_id'], []).append(name)
    shaped = {}
    for name in sorted(views):
        value = views[name]
        shaped[name] = ([view_metadata(t, tensors, storages) for t in value]
                        if type(value) in (list, tuple)
                        else view_metadata(value, tensors, storages))
    # Raw allocation storage only, never sum aliases or overlapping shaped views.
    sizes = {}
    for metadata in raw.values():
        sizes[metadata['storage_id']] = metadata['storage_bytes']
    # Worker-side alias map: which raw-tensor layer names resolve to the same
    # backing storage (identity of the storage object, never its data_ptr()).
    alias_groups = [dict(storage_id=storage_id, layer_names=sorted(names))
                     for storage_id, names in sorted(storage_layers.items())
                     if len(names) > 1]
    return dict(raw_tensors=raw, views=shaped,
                distinct_raw_storage_bytes=sum(sizes.values()),
                distinct_raw_storages=len(sizes),
                storage_alias_groups=alias_groups,
                identity_scope='this snapshot; sequential IDs, not addresses')


def snapshot(stage, **values):
    """Pure metadata traversal, separately testable; never traverses unknown kwargs."""
    if stage not in STAGES:
        raise ValueError('unknown startup stage')
    missing_fields = []
    result = {'config': config_metadata(values['vllm_config'])}
    if stage == 'engine_projection':
        # Unchanged from OLD: same call, same args, same scope.
        result['workers'] = [dict(worker_index=i,
                                  available_bytes=scalar(values['available_memory'][i]),
                                  registered_specs=specs_metadata(specs),
                                  groups=groups_metadata(values['projected_groups'][i]))
                             for i, specs in enumerate(values['kv_cache_specs'])]
    elif stage == 'engine_final':
        cache = values['kv_cache_config']
        result.update(cache=cache_metadata(cache, missing_fields),
                      runtime_reported_num_tokens=scalar(values['num_tokens']),
                      runtime_reported_max_concurrency=scalar(values['max_concurrency']))
        # NEW calls update_kv_cache_capacity once on the already-merged
        # scheduler config, not per-worker in a loop -- `kv_cache_configs`
        # (the full list, needed to recover worker_index by identity) and the
        # matching `available_memory` entry are simply not in scope there
        # any more. Derive them only if a caller still supplies the OLD kwargs.
        kv_cache_configs = values.get('kv_cache_configs', MISSING)
        worker_index = None
        if kv_cache_configs is not MISSING:
            worker_index = next((i for i, item in enumerate(kv_cache_configs)
                                 if item is cache), None)
        if worker_index is None:
            missing_fields.append('worker_index')
        result['worker_index'] = worker_index
        available_memory = values.get('available_memory', MISSING)
        if worker_index is not None and available_memory is not MISSING:
            result['effective_available_bytes'] = scalar(available_memory[worker_index])
        else:
            result['effective_available_bytes'] = None
            missing_fields.append('effective_available_bytes')
    else:
        kv_cache_config = values['kv_cache_config']
        result.update(cache=cache_metadata(kv_cache_config, missing_fields),
                      aliases=aliases_metadata(values['shared_layers']),
                      declared_aliases=declared_aliases(values['forward_context']),
                      kernel_block_sizes=integer_list(values['kernel_block_sizes']),
                      device=metadata_text(values['device']))
        # cache_dtype was dropped from init_kv_cache's signature entirely, but
        # it is still reachable off vllm_config (always in scope) -- this is
        # a full derivation, not a gap.
        cache_dtype = values.get('cache_dtype', MISSING)
        if cache_dtype is MISSING:
            cache_dtype = getattr(values['vllm_config'].cache_config, 'cache_dtype', MISSING)
        if cache_dtype is MISSING:
            result['cache_dtype'] = None
            missing_fields.append('cache_dtype')
        else:
            result['cache_dtype'] = scalar(cache_dtype)
        # attn_groups (backend + spec per attention-builder group) no longer
        # reaches this call site -- it now lives one frame up, on the model
        # runner's own self.attn_groups. Everything else it used to carry
        # (group_id, layer_names, is_eagle_group, spec) is available directly
        # off kv_cache_config.kv_cache_groups (also emitted under cache.groups
        # above); only the backend class name is a genuine gap. Flattened
        # (OLD's outer per-ubatch list carried no information we still have).
        attn_groups = values.get('attn_groups', MISSING)
        if attn_groups is not MISSING:
            result['attention_groups'] = [
                dict(group_id=scalar(g.kv_cache_group_id), backend=class_name(g.backend),
                     layer_names=[scalar(n) for n in g.layer_names],
                     spec=spec_metadata(g.kv_cache_spec))
                for group in attn_groups for g in group]
        else:
            result['attention_groups'] = [
                dict(group_id=i, layer_names=[scalar(n) for n in group.layer_names],
                     is_eagle_group=scalar(group.is_eagle_group), backend=None,
                     spec=spec_metadata(group.kv_cache_spec))
                for i, group in enumerate(kv_cache_config.kv_cache_groups)]
            missing_fields.append('attention_groups[].backend')
        if stage == 'worker_postbind':
            result['tensor_metadata'] = tensor_snapshots(values['raw_tensors'], values['kv_caches'])
            result['alias_same_view_object'] = {
                name: values['kv_caches'].get(name, MISSING) is values['kv_caches'].get(target, None)
                for name, target in sorted(values['shared_layers'].items())}
    if missing_fields:
        result['missing_fields'] = sorted(set(missing_fields))
    return result


def write_record(record, directory, run_id):
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9._-]{0,95}', run_id):
        raise ValueError('invalid observer run ID')
    root = Path(directory)
    if not root.is_absolute() or root.is_symlink() or not root.is_dir():
        raise ValueError('observer directory must be precreated, absolute and not a symlink')
    host = re.sub(r'[^A-Za-z0-9._-]', '_', socket.gethostname())
    path = root / f'{run_id}.{host}.{os.getpid()}.jsonl'
    payload = (json.dumps(record, sort_keys=True, separators=(',', ':'),
                          allow_nan=False) + '\n').encode('utf-8')
    if len(payload) > 16 * 1024 * 1024:
        raise ValueError('observer metadata exceeds size bound')
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_APPEND | os.O_NOFOLLOW, 0o600)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or stat.S_IMODE(info.st_mode) != 0o600 or info.st_uid != os.geteuid():
            raise PermissionError('observer receipt file is not owned regular 0600')
        remaining = memoryview(payload)
        while remaining:
            written = os.write(fd, remaining)
            if written <= 0:
                raise OSError('short metadata write')
            remaining = remaining[written:]
    finally:
        os.close(fd)


def emit(stage, **values):
    if os.environ.get('VLLM_STARTUP_OBSERVER') != '1':
        return False
    try:
        if stage not in STAGES:
            raise ValueError('unknown startup stage')
        run_id = os.environ['VLLM_STARTUP_OBSERVER_RUN_ID']
        manifest = os.environ['VLLM_STARTUP_OBSERVER_MANIFEST_SHA256']
        if not re.fullmatch(r'[0-9a-f]{64}', manifest):
            raise ValueError('invalid observer manifest fingerprint')
        record = dict(schema=SCHEMA, stage=stage, run_id=run_id,
                      overlay_manifest_sha256=manifest, pid=os.getpid(),
                      hostname=socket.gethostname(),
                      timestamp=datetime.now(ZoneInfo('Australia/Sydney')).isoformat(),
                      metadata=snapshot(stage, **values))
        write_record(record, os.environ['VLLM_STARTUP_OBSERVER_DIR'], run_id)
        return True
    except Exception as error:
        # Do not include exception text: arbitrary failure messages can contain
        # sensitive config values. Missing events/errors fail C4 externally.
        try:
            safe_stage = stage if stage in STAGES else 'unknown'
            sys.stderr.write(f'[STARTUP_OBSERVER_INCOMPLETE] stage={safe_stage} error={type(error).__name__}\n')
        except Exception:
            pass
        return False
